version: "3.9"

services:
  flutter-env:
    build: .
    container_name: game_controller_dev
    # Maps your local project folder into the container so changes reflect instantly
    volumes:
      - .:/app
      # Mount USB device bus to access connected Android devices
      - /dev/bus/usb:/dev/bus/usb
    # Use host network mode to access ADB devices
    network_mode: "host"
    # Keeps the container alive so you can connect VS Code to it
    tty: true
    stdin_open: true
